// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5114.FentonRobotBuilderJava.commands;
import org.usfirst.frc5114.AutonCommand.AutonCommand;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class LiftBinAndGetCloseToDriver extends CommandGroup {
    
    public  LiftBinAndGetCloseToDriver() {
    	// Note that command groups are built (constructed) when the robot program is initialized
    	// so using case statements in a command group is not recommended because the decisions made are only made once
    	
    	System.out.println("Begin LiftBinAndGetCloseToDriver Command Group");    	
		// Auton #5, case 4
		
		// Lift rear for 1s
		new AutonCommand("RL,0.75,1.0,S", this);
		
		// Stop Rear Lift
		new AutonCommand("RS,0.0,0.125,S", this);
		
		// Drive south 60% 3.35s
		new AutonCommand("DS,0.6,1.001,S", this);
		
		// Stop drive train for 0.125s
		new AutonCommand("RL,0.0,0.125,S", this);
		
		System.out.println("End LiftBinAndGetCloseToDriver Command Group");		
    }
}
