// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5114.FentonRobotBuilderJava.commands;
import org.usfirst.frc5114.AutonCommand.AutonCommand;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class TestAutonCommands extends CommandGroup {
    
    public  TestAutonCommands() {
    	// Note that command groups are built (constructed) when the robot program is initialized
    	// so using case statements in a command group is not recommended because the decisions made are only made once
    	
		// Test
    	System.out.println("Begin TestAutonCommands Command Group");
    	
    	// Drive South for 1s at 60%
    	new AutonCommand("DS,0.6,1.0,S", this);
    	
		// Stop drive train for 0.125s
		new AutonCommand("D0,0.0,0.125,S", this);
    	
    	// Drive North for 1s at 60%
    	new AutonCommand("DN,0.6,1.0,S", this);
    	
		// Stop drive train for 0.125s
		new AutonCommand("D0,0.0,0.125,S", this);
		
		System.out.println("End TestAutonCommands Command Group");		
    }
}
